config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users do
    collection do
      post :import
    end
  end
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  # validates_format_of :first_name, :last_name, with: /\A[a-zA-Z]+\z/, message: "can only contain letters"
  validates :email_id, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(5)
    @result = flash[:result]
  end

  def import
    file = params[:file]
    return redirect_to users_path, notice: 'Please upload a file' if file.nil?

    @result = ExcelUpload.new(file).process
    flash[:result] = @result
    if @result[:error].present?
      redirect_to users_path, alert: @result[:error]
    else
      redirect_to users_path, notice: 'Users imported!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcelUploadApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'users' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_display_users.html.erb
<h2>Users: <%= @users.total_count %></h2>

<table class="user-table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email ID</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination">
  <%= paginate @users %>
</div>

app/views/users/_import_result.html.erb
<div class="result">
  <h3>Upload Results:</h3>
  <p>Total User Data Rows: <%= @result["total_rows"] %></p>
  <p>Successfully Added: <%= @result["success_count"] %></p>
  <p>Failed: <%= @result["failures"].present? ? @result["failures"].count : 0 %></p>
  <% if @result["failures"].present? %>
    <h3>Failure Details:</h3>
    <ul>
      <% @result["failures"].each do |failure| %>
        <li>
          Row <%= failure["index"] %>: <%= failure["errors"].join(', ') %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="import-section">
  <%= form_with url: import_users_path, method: :post do |form| %>
    <%= form.file_field :file, accept: ".xlsx" %>
    <%= form.button "Import", class: "btn-primary" %>
  <% end %>
</div>

<div class="flash-notice" style="color: green">
  <p><%= notice %></p>
</div>

<div class="flash-alert" style="color: red">
  <p><%= alert %></p>
</div>

<%= render partial: 'import_result', locals: { result: @result } if @result.present? && alert.blank?%>
<%= render partial: 'display_users', locals: { users: @users } if @users.present? %>